// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLoggedInUser() {
  return window['go']['app']['Auth']['GetLoggedInUser']();
}

export function Login(arg1, arg2) {
  return window['go']['app']['Auth']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['app']['Auth']['Logout']();
}

export function SignUp(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Auth']['SignUp'](arg1, arg2, arg3, arg4);
}
