// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetLoggedInUser():Promise<model.User>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Logout():Promise<void>;

export function SignUp(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;
