// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {pgx} from '../models';
import {uuid} from '../models';

export function AddPostgresConnection(arg1:model.Connection):Promise<boolean>;

export function BuildPostgresConnConfig(arg1:model.Connection):Promise<pgx.ConnConfig>;

export function EstablishPostgresConnection(arg1:number):Promise<Array<model.Database>>;

export function EstablishPostgresDatabaseConnection(arg1:number,arg2:string):Promise<model.Database>;

export function ExecuteQuery(arg1:uuid.UUID,arg2:string,arg3:number):Promise<model.QueryResult>;

export function GetAllConnections():Promise<Array<model.Connection>>;

export function GetAllDatabaseColumns(arg1:uuid.UUID):Promise<Array<string>>;

export function GetAllPostgresTables(arg1:uuid.UUID):Promise<Array<string>>;

export function GetPostgresServerDatabases(arg1:number,arg2:uuid.UUID,arg3:string,arg4:string,arg5:string):Promise<Array<model.Database>>;

export function GetSqlite3Version():Promise<string>;

export function GetTableData(arg1:uuid.UUID,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<model.QueryResult>;

export function GetTableInfo(arg1:uuid.UUID,arg2:string):Promise<model.TableInfo>;

export function RefreshPostgresDatabase(arg1:number,arg2:string,arg3:string,arg4:string):Promise<model.Database>;

export function TerminateAllDatabaseConnections():Promise<void>;

export function TerminatePostgresDatabaseConnection(arg1:string):Promise<boolean>;

export function TestConnectPostgres(arg1:model.Connection):Promise<boolean>;

export function UpdateTabOutput(arg1:number,arg2:model.Output):Promise<void>;
