// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddColumn(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['AddColumn'](arg1, arg2, arg3);
}

export function AddConstraint(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['AddConstraint'](arg1, arg2, arg3);
}

export function AddPostgresConnection(arg1) {
  return window['go']['app']['Connections']['AddPostgresConnection'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['app']['Connections']['CancelQuery'](arg1);
}

export function CreateIndex(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['CreateIndex'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['Connections']['DeleteConnection'](arg1);
}

export function DeleteRows(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['DeleteRows'](arg1, arg2, arg3);
}

export function DropColumn(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Connections']['DropColumn'](arg1, arg2, arg3, arg4);
}

export function DropConstraint(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Connections']['DropConstraint'](arg1, arg2, arg3, arg4);
}

export function DropIndex(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Connections']['DropIndex'](arg1, arg2, arg3, arg4);
}

export function EstablishPostgresConnection(arg1) {
  return window['go']['app']['Connections']['EstablishPostgresConnection'](arg1);
}

export function EstablishPostgresDatabaseConnection(arg1, arg2) {
  return window['go']['app']['Connections']['EstablishPostgresDatabaseConnection'](arg1, arg2);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['ExecuteQuery'](arg1, arg2, arg3);
}

export function GetAllConnections() {
  return window['go']['app']['Connections']['GetAllConnections']();
}

export function GetAllDatabaseColumns(arg1) {
  return window['go']['app']['Connections']['GetAllDatabaseColumns'](arg1);
}

export function GetAllPostgresTables(arg1) {
  return window['go']['app']['Connections']['GetAllPostgresTables'](arg1);
}

export function GetColumnDefinition(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['GetColumnDefinition'](arg1, arg2, arg3);
}

export function GetConnection(arg1) {
  return window['go']['app']['Connections']['GetConnection'](arg1);
}

export function GetConstraintDefinition(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['GetConstraintDefinition'](arg1, arg2, arg3);
}

export function GetIndexDefinition(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['GetIndexDefinition'](arg1, arg2, arg3);
}

export function GetPostgresServerDatabases(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['Connections']['GetPostgresServerDatabases'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSchemaEditorOptions(arg1) {
  return window['go']['app']['Connections']['GetSchemaEditorOptions'](arg1);
}

export function GetSqlite3Version() {
  return window['go']['app']['Connections']['GetSqlite3Version']();
}

export function GetTableColumnsMeta(arg1, arg2) {
  return window['go']['app']['Connections']['GetTableColumnsMeta'](arg1, arg2);
}

export function GetTableDDL(arg1, arg2) {
  return window['go']['app']['Connections']['GetTableDDL'](arg1, arg2);
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['Connections']['GetTableData'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function GetTableInfo(arg1, arg2) {
  return window['go']['app']['Connections']['GetTableInfo'](arg1, arg2);
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['InsertRow'](arg1, arg2, arg3);
}

export function RefreshPostgresDatabase(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Connections']['RefreshPostgresDatabase'](arg1, arg2, arg3, arg4);
}

export function TerminateAllDatabaseConnections() {
  return window['go']['app']['Connections']['TerminateAllDatabaseConnections']();
}

export function TerminatePostgresDatabaseConnection(arg1, arg2) {
  return window['go']['app']['Connections']['TerminatePostgresDatabaseConnection'](arg1, arg2);
}

export function TestConnectPostgres(arg1) {
  return window['go']['app']['Connections']['TestConnectPostgres'](arg1);
}

export function TypeConnectionTable() {
  return window['go']['app']['Connections']['TypeConnectionTable']();
}

export function UpdateCells(arg1, arg2) {
  return window['go']['app']['Connections']['UpdateCells'](arg1, arg2);
}

export function UpdateColumn(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Connections']['UpdateColumn'](arg1, arg2, arg3, arg4);
}

export function UpdateConnection(arg1) {
  return window['go']['app']['Connections']['UpdateConnection'](arg1);
}

export function UpdateConstraint(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Connections']['UpdateConstraint'](arg1, arg2, arg3, arg4);
}

export function UpdateIndex(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Connections']['UpdateIndex'](arg1, arg2, arg3, arg4);
}
