// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddQueryHistory(arg1:string):Promise<void>;

export function GetQueryHistory():Promise<Array<model.QueryHistory>>;
