// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddQueryHistory(arg1) {
  return window['go']['app']['QueryHistory']['AddQueryHistory'](arg1);
}

export function GetQueryHistory() {
  return window['go']['app']['QueryHistory']['GetQueryHistory']();
}
