// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteSavedQuery(arg1:number):Promise<void>;

export function GetSavedQueries():Promise<Array<model.SavedQuery>>;

export function SaveQuery(arg1:string,arg2:string):Promise<void>;
