// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveQuery(arg1, arg2) {
  return window['go']['app']['SavedQueries']['SaveQuery'](arg1, arg2);
}

export function GetSavedQueries() {
  return window['go']['app']['SavedQueries']['GetSavedQueries']();
}

export function DeleteSavedQuery(arg1) {
  return window['go']['app']['SavedQueries']['DeleteSavedQuery'](arg1);
}
