// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbmx} from '../models';

export function AddProviderAPIKey(arg1:string,arg2:string):Promise<void>;

export function DeleteProviderAPIKey(arg1:string,arg2:string):Promise<void>;

export function DisableStardustAI():Promise<void>;

export function EnableStardustAI():Promise<dbmx.Customer>;

export function ListUserProviders():Promise<Array<dbmx.UserProvider>>;

export function SwitchDefaultKey(arg1:boolean):Promise<void>;

export function UpdateProviderAPIKey(arg1:string,arg2:string,arg3:string):Promise<void>;
