// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProviderAPIKey(arg1, arg2) {
  return window['go']['app']['Stardust']['AddProviderAPIKey'](arg1, arg2);
}

export function Chat(arg1, arg2, arg3) {
  return window['go']['app']['Stardust']['Chat'](arg1, arg2, arg3);
}

export function DeleteProviderAPIKey(arg1, arg2) {
  return window['go']['app']['Stardust']['DeleteProviderAPIKey'](arg1, arg2);
}

export function DisableStardustAI() {
  return window['go']['app']['Stardust']['DisableStardustAI']();
}

export function EnableStardustAI() {
  return window['go']['app']['Stardust']['EnableStardustAI']();
}

export function GetSchemaContext(arg1) {
  return window['go']['app']['Stardust']['GetSchemaContext'](arg1);
}

export function ListAvailableModels() {
  return window['go']['app']['Stardust']['ListAvailableModels']();
}

export function ListProviders() {
  return window['go']['app']['Stardust']['ListProviders']();
}

export function SwitchDefaultKey(arg1) {
  return window['go']['app']['Stardust']['SwitchDefaultKey'](arg1);
}

export function UpdateProviderAPIKey(arg1, arg2, arg3) {
  return window['go']['app']['Stardust']['UpdateProviderAPIKey'](arg1, arg2, arg3);
}
