// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbmx} from '../models';

export function DisableStardustAI():Promise<void>;

export function EnableStardustAI():Promise<dbmx.Customer>;

export function SwitchDefaultKey(arg1:boolean):Promise<void>;
