// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableStardustAI() {
  return window['go']['app']['Stardust']['DisableStardustAI']();
}

export function EnableStardustAI() {
  return window['go']['app']['Stardust']['EnableStardustAI']();
}

export function SwitchDefaultKey(arg1) {
  return window['go']['app']['Stardust']['SwitchDefaultKey'](arg1);
}
