// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddTab(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string,arg8:string):Promise<model.Tab>;

export function DeleteTab(arg1:number):Promise<model.Tab>;

export function GetAllTabs():Promise<Array<model.Tab>>;

export function SaveActiveDBProps(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveNewChatMessage(arg1:number,arg2:model.AIMsg):Promise<void>;

export function SetActiveTab(arg1:number):Promise<model.Tab>;

export function UpdateTabEditorContent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;
