package app

// Schema-editor tests. These drive the bound Connections methods against a real
// postgres over a real pgxpool, which is the only way to check work whose whole
// output is SQL text the server has to accept: a type modifier that survives the
// round trip, a transaction that rolls a half-applied edit back, a constraint body
// rendered byte-for-byte the way pg_get_constraintdef prints it.
//
// They need a server, so they skip unless DBMX_LIVE_PG names one. Anything reachable
// works; a throwaway container is enough:
//
//	docker run -d --name dbmx-pg -e POSTGRES_PASSWORD=dbmx -e POSTGRES_DB=dbmxtest \
//	  -p 55432:5432 postgres:16
//	DBMX_LIVE_PG='postgres://postgres:dbmx@localhost:55432/dbmxtest?sslmode=disable' \
//	  go test ./app -run TestLive -v
//
// Point it at a scratch database only: the fixtures drop and recreate their tables.

import (
	"context"
	"database/sql"
	"dbmx/model"
	"fmt"
	"os"
	"testing"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

const liveTabID = int64(1)

func liveConnections(t *testing.T) (*Connections, func()) {
	t.Helper()

	dsn := os.Getenv("DBMX_LIVE_PG")
	if dsn == "" {
		t.Skip("DBMX_LIVE_PG not set")
	}

	// The app reads the tab's active pool out of local sqlite, so stand up the
	// smallest table poolForTab needs.
	// A bare ":memory:" database belongs to one connection, and database/sql
	// opens more on demand: the moment a test touches sqlite from two goroutines
	// the second one lands on an empty database and the tabs row vanishes. A
	// named shared-cache database is the same store on every connection, and one
	// connection keeps the writes serialised.
	db, err := sql.Open("sqlite3", fmt.Sprintf("file:%s?mode=memory&cache=shared", uuid.NewString()))
	if err != nil {
		t.Fatalf("sqlite open: %v", err)
	}
	db.SetMaxOpenConns(1)
	poolID := uuid.New()
	if _, err := db.Exec(`CREATE TABLE tabs (id INTEGER PRIMARY KEY, active_db_id TEXT)`); err != nil {
		t.Fatalf("create tabs: %v", err)
	}
	if _, err := db.Exec(`INSERT INTO tabs (id, active_db_id) VALUES (?, ?)`, liveTabID, poolID.String()); err != nil {
		t.Fatalf("insert tab: %v", err)
	}

	config, err := pgx.ParseConfig(dsn)
	if err != nil {
		t.Fatalf("parse dsn: %v", err)
	}
	pm := NewPoolManager()
	if _, err := pm.AddPool(poolID, config, 1); err != nil {
		t.Fatalf("add pool: %v", err)
	}

	c := NewConnections(db, pm)
	return c, func() {
		_ = pm.DeletePool(poolID, 1)
		_ = db.Close()
	}
}

// exec runs raw SQL through the tab's pool, for fixtures and assertions.
func exec(t *testing.T, c *Connections, query string) {
	t.Helper()
	pool, err := c.poolForTab(liveTabID)
	if err != nil {
		t.Fatalf("pool: %v", err)
	}
	if _, err := pool.Exec(context.Background(), query); err != nil {
		t.Fatalf("exec %q: %v", query, err)
	}
}

func scalar(t *testing.T, c *Connections, query string) string {
	t.Helper()
	pool, err := c.poolForTab(liveTabID)
	if err != nil {
		t.Fatalf("pool: %v", err)
	}
	var value *string
	if err := pool.QueryRow(context.Background(), query).Scan(&value); err != nil {
		t.Fatalf("query %q: %v", query, err)
	}
	if value == nil {
		return "<nil>"
	}
	return *value
}

func TestLiveSchema(t *testing.T) {
	c, cleanup := liveConnections(t)
	defer cleanup()

	exec(t, c, `DROP TABLE IF EXISTS orders, customers CASCADE`)
	exec(t, c, `DROP TYPE IF EXISTS mood CASCADE`)
	exec(t, c, `CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy')`)
	exec(t, c, `CREATE TABLE customers (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email text NOT NULL)`)
	exec(t, c, `CREATE TABLE orders (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id integer)`)

	t.Run("options come from the catalog", func(t *testing.T) {
		options, err := c.GetSchemaEditorOptions(liveTabID)
		if err != nil {
			t.Fatalf("GetSchemaEditorOptions: %v", err)
		}
		var foundEnum *model.TypeOption
		common := 0
		for i, option := range options.Types {
			if option.Name == "mood" {
				foundEnum = &options.Types[i]
			}
			if option.IsCommon {
				common++
			}
		}
		if foundEnum == nil {
			t.Fatal("the database's own enum is missing from the type list")
		}
		if foundEnum.Kind != "enum" || len(foundEnum.EnumValues) != 3 {
			t.Fatalf("enum came back as %+v", *foundEnum)
		}
		t.Logf("types=%d (common=%d) methods=%v tables=%v collations=%d",
			len(options.Types), common, options.IndexMethods, options.Tables, len(options.Collations))
	})

	// Every column type the add-column form can be pointed at, including the ones
	// InsertRow's comment calls out as easy to corrupt.
	t.Run("add a column of every type family", func(t *testing.T) {
		types := []string{
			"text", "character varying(255)", "character(3)", "numeric(10,2)", "bigint",
			"smallint", "double precision", "real", "boolean", "date",
			"timestamp with time zone", "timestamp without time zone", "time without time zone",
			"interval", "uuid", "json", "jsonb", "xml", "bytea", "inet", "cidr", "macaddr",
			"money", "bit(4)", "bit varying(8)", "int4range", "tsvector", "point", "polygon",
			"text[]", "integer[]", "jsonb[]", "mood", "mood[]", "citext_missing_on_purpose",
		}
		for i, dataType := range types {
			name := fmt.Sprintf("c%02d", i)
			err := c.AddColumn(liveTabID, "customers", model.ColumnDefinition{
				Name: name, DataType: dataType, IsNullable: true,
			})
			if dataType == "citext_missing_on_purpose" {
				if err == nil {
					t.Fatal("an unknown type was accepted")
				}
				t.Logf("rejected unknown type: %v", err)
				continue
			}
			if err != nil {
				t.Fatalf("AddColumn %s %s: %v", name, dataType, err)
			}
			got := scalar(t, c, fmt.Sprintf(
				`SELECT format_type(atttypid, atttypmod) FROM pg_attribute
				 WHERE attrelid = 'public.customers'::regclass AND attname = '%s'`, name))
			if got != dataType {
				t.Fatalf("column %s: asked for %q, postgres stored %q", name, dataType, got)
			}
		}
		t.Logf("%d column types round-tripped with their modifiers intact", len(types)-1)
	})

	t.Run("reject a type that would comment out the statement", func(t *testing.T) {
		for _, bad := range []string{"text-- x", "text; DROP TABLE customers", "text) --"} {
			if err := c.AddColumn(liveTabID, "customers", model.ColumnDefinition{
				Name: "evil", DataType: bad, IsNullable: true,
			}); err == nil {
				t.Fatalf("accepted %q as a type", bad)
			}
		}
		t.Log("comment and statement-splitting shapes rejected")
	})

	t.Run("add a column with default, not null and comment", func(t *testing.T) {
		if err := c.AddColumn(liveTabID, "customers", model.ColumnDefinition{
			Name: "status", DataType: "text", IsNullable: false,
			DefaultValue: "'draft'", Comment: "Workflow state",
		}); err != nil {
			t.Fatalf("AddColumn: %v", err)
		}
		def, err := c.GetColumnDefinition(liveTabID, "customers", "status")
		if err != nil {
			t.Fatalf("GetColumnDefinition: %v", err)
		}
		if def.IsNullable || def.DefaultValue != "'draft'::text" || def.Comment != "Workflow state" {
			t.Fatalf("round-trip lost something: %+v", *def)
		}
		t.Logf("round-tripped: %+v", *def)
	})

	t.Run("add an identity and a generated column", func(t *testing.T) {
		if err := c.AddColumn(liveTabID, "customers", model.ColumnDefinition{
			Name: "seq", DataType: "bigint", Identity: "ALWAYS",
		}); err != nil {
			t.Fatalf("identity AddColumn: %v", err)
		}
		if err := c.AddColumn(liveTabID, "customers", model.ColumnDefinition{
			Name: "email_lower", DataType: "text", IsNullable: true,
			GeneratedExpression: "lower(email)",
		}); err != nil {
			t.Fatalf("generated AddColumn: %v", err)
		}
		identity, err := c.GetColumnDefinition(liveTabID, "customers", "seq")
		if err != nil {
			t.Fatalf("GetColumnDefinition seq: %v", err)
		}
		generated, err := c.GetColumnDefinition(liveTabID, "customers", "email_lower")
		if err != nil {
			t.Fatalf("GetColumnDefinition email_lower: %v", err)
		}
		if identity.Identity != "ALWAYS" {
			t.Fatalf("identity lost: %+v", *identity)
		}
		if generated.GeneratedExpression == "" || generated.DefaultValue != "" {
			t.Fatalf("generated expression mis-read: %+v", *generated)
		}
		t.Logf("identity=%q generated=%q", identity.Identity, generated.GeneratedExpression)
	})

	t.Run("mutually exclusive value sources are refused", func(t *testing.T) {
		if err := c.AddColumn(liveTabID, "customers", model.ColumnDefinition{
			Name: "clash", DataType: "integer", Identity: "ALWAYS", DefaultValue: "1",
		}); err == nil {
			t.Fatal("identity plus default was accepted")
		}
		if err := c.AddColumn(liveTabID, "customers", model.ColumnDefinition{
			Name: "clash", DataType: "integer", GeneratedExpression: "1", DefaultValue: "1",
		}); err == nil {
			t.Fatal("generated plus default was accepted")
		}
		t.Log("refused identity+default and generated+default")
	})

	t.Run("edit a column: rename, retype, default, nullability, comment at once", func(t *testing.T) {
		exec(t, c, `INSERT INTO customers (email, status) VALUES ('A@Example.com', 'live')`)

		if err := c.UpdateColumn(liveTabID, "customers", "status", model.ColumnDefinition{
			Name: "state", DataType: "character varying(32)", IsNullable: true,
			DefaultValue: "'new'", Comment: "Renamed and retyped",
		}); err != nil {
			t.Fatalf("UpdateColumn: %v", err)
		}
		def, err := c.GetColumnDefinition(liveTabID, "customers", "state")
		if err != nil {
			t.Fatalf("GetColumnDefinition: %v", err)
		}
		if def.DataType != "character varying(32)" || !def.IsNullable || def.Comment != "Renamed and retyped" {
			t.Fatalf("edit did not land: %+v", *def)
		}
		kept := scalar(t, c, `SELECT state FROM customers WHERE email = 'A@Example.com'`)
		if kept != "live" {
			t.Fatalf("existing data was lost: %q", kept)
		}
		t.Logf("renamed status->state, retyped to %s, data preserved (%q)", def.DataType, kept)
	})

	t.Run("a failing edit rolls the whole statement set back", func(t *testing.T) {
		before, err := c.GetColumnDefinition(liveTabID, "customers", "state")
		if err != nil {
			t.Fatalf("GetColumnDefinition: %v", err)
		}
		// The rename would succeed; SET NOT NULL cannot, because a row holds NULL.
		exec(t, c, `INSERT INTO customers (email, state) VALUES ('null-state@example.com', NULL)`)
		err = c.UpdateColumn(liveTabID, "customers", "state", model.ColumnDefinition{
			Name: "state_renamed", DataType: before.DataType, IsNullable: false,
		})
		if err == nil {
			t.Fatal("SET NOT NULL over a NULL row was accepted")
		}
		after, getErr := c.GetColumnDefinition(liveTabID, "customers", "state")
		if getErr != nil {
			t.Fatalf("the rename was not rolled back, column is gone: %v", getErr)
		}
		if after.Name != "state" {
			t.Fatalf("rename survived a failed edit: %+v", *after)
		}
		t.Logf("rejected (%v) and the rename rolled back with it", err)
		exec(t, c, `DELETE FROM customers WHERE email = 'null-state@example.com'`)
	})

	t.Run("a generated expression cannot be rewritten in place", func(t *testing.T) {
		err := c.UpdateColumn(liveTabID, "customers", "email_lower", model.ColumnDefinition{
			Name: "email_lower", DataType: "text", IsNullable: true,
			GeneratedExpression: "upper(email)",
		})
		if err == nil {
			t.Fatal("a rewritten generation expression was accepted")
		}
		t.Logf("refused with: %v", err)

		// Clearing it drops the expression and keeps the values.
		if err := c.UpdateColumn(liveTabID, "customers", "email_lower", model.ColumnDefinition{
			Name: "email_lower", DataType: "text", IsNullable: true,
		}); err != nil {
			t.Fatalf("clearing the expression: %v", err)
		}
		def, err := c.GetColumnDefinition(liveTabID, "customers", "email_lower")
		if err != nil {
			t.Fatalf("GetColumnDefinition: %v", err)
		}
		if def.GeneratedExpression != "" {
			t.Fatalf("expression survived the drop: %+v", *def)
		}
		if kept := scalar(t, c, `SELECT email_lower FROM customers WHERE email = 'A@Example.com'`); kept != "a@example.com" {
			t.Fatalf("values lost when the expression was dropped: %q", kept)
		}
		t.Log("cleared the expression and kept the computed values")
	})

	t.Run("drop a column, restrict then cascade", func(t *testing.T) {
		exec(t, c, `CREATE VIEW customer_emails AS SELECT email FROM customers`)
		if err := c.DropColumn(liveTabID, "customers", "email", false); err == nil {
			t.Fatal("RESTRICT dropped a column a view depends on")
		} else {
			t.Logf("RESTRICT refused: %v", err)
		}
		if err := c.DropColumn(liveTabID, "customers", "c00", false); err != nil {
			t.Fatalf("DropColumn: %v", err)
		}
		if err := c.DropColumn(liveTabID, "customers", "email", true); err != nil {
			t.Fatalf("cascade DropColumn: %v", err)
		}
		t.Log("dropped under RESTRICT and under CASCADE")
	})

	t.Run("create, edit and drop an index", func(t *testing.T) {
		if err := c.CreateIndex(liveTabID, "customers", model.IndexDefinition{
			Name: "customers_state_idx", Method: "btree",
			Columns: []string{"state DESC NULLS LAST"}, Include: []string{"id"},
			Where: "state IS NOT NULL", Comment: "partial, with a payload",
		}); err != nil {
			t.Fatalf("CreateIndex: %v", err)
		}
		def, err := c.GetIndexDefinition(liveTabID, "customers", "customers_state_idx")
		if err != nil {
			t.Fatalf("GetIndexDefinition: %v", err)
		}
		if len(def.Columns) != 1 || len(def.Include) != 1 || def.Where == "" || def.Comment == "" {
			t.Fatalf("index round-trip lost something: %+v", *def)
		}
		t.Logf("round-tripped: columns=%v include=%v where=%q", def.Columns, def.Include, def.Where)

		// Rename only -- postgres can do this in place, which the unchanged oid proves:
		// a rebuild would have produced a different index object.
		oidBefore := scalar(t, c, `SELECT 'public.customers_state_idx'::regclass::oid::text`)
		if err := c.UpdateIndex(liveTabID, "customers", "customers_state_idx", model.IndexDefinition{
			Name: "customers_state_partial_idx", Method: def.Method, IsUnique: def.IsUnique,
			Columns: def.Columns, Include: def.Include, Where: def.Where, Comment: def.Comment,
		}); err != nil {
			t.Fatalf("rename UpdateIndex: %v", err)
		}
		oidAfter := scalar(t, c, `SELECT 'public.customers_state_partial_idx'::regclass::oid::text`)
		if oidBefore != oidAfter {
			t.Fatalf("a name-only change rebuilt the index (oid %s -> %s)", oidBefore, oidAfter)
		}
		if kept := scalar(t, c, `SELECT obj_description('public.customers_state_partial_idx'::regclass, 'pg_class')`); kept != "partial, with a payload" {
			t.Fatalf("the comment was lost in the rename: %q", kept)
		}

		// A real redefinition -- drop and create, in one transaction.
		if err := c.UpdateIndex(liveTabID, "customers", "customers_state_partial_idx", model.IndexDefinition{
			Name: "customers_state_lower_idx", Method: "btree", IsUnique: true,
			Columns: []string{"lower(state)"}, Comment: "rebuilt",
		}); err != nil {
			t.Fatalf("redefine UpdateIndex: %v", err)
		}
		rebuilt, err := c.GetIndexDefinition(liveTabID, "customers", "customers_state_lower_idx")
		if err != nil {
			t.Fatalf("GetIndexDefinition after rebuild: %v", err)
		}
		if !rebuilt.IsUnique || rebuilt.Where != "" || rebuilt.Comment != "rebuilt" {
			t.Fatalf("rebuild did not land: %+v", *rebuilt)
		}
		t.Logf("renamed in place, then rebuilt as %v unique=%v", rebuilt.Columns, rebuilt.IsUnique)

		// A gist index, to prove the method list is not decorative.
		if err := c.CreateIndex(liveTabID, "customers", model.IndexDefinition{
			Name: "customers_c28_gist", Method: "gist", Columns: []string{"c28"},
		}); err != nil {
			t.Fatalf("gist CreateIndex: %v", err)
		}
		if err := c.CreateIndex(liveTabID, "customers", model.IndexDefinition{
			Name: "bad_method_idx", Method: "nosuchmethod", Columns: []string{"id"},
		}); err == nil {
			t.Fatal("an unknown index method was accepted")
		}

		if err := c.DropIndex(liveTabID, "customers", "customers_c28_gist", false); err != nil {
			t.Fatalf("DropIndex: %v", err)
		}
		t.Log("gist index created and dropped; unknown method refused")
	})

	t.Run("a constraint's index is not editable as an index", func(t *testing.T) {
		pkName := scalar(t, c, `SELECT conname FROM pg_constraint
			WHERE conrelid = 'public.customers'::regclass AND contype = 'p'`)
		def, err := c.GetIndexDefinition(liveTabID, "customers", pkName)
		if err != nil {
			t.Fatalf("GetIndexDefinition: %v", err)
		}
		if !def.IsConstraint {
			t.Fatal("the primary key's index was not flagged as constraint-backed")
		}
		if err := c.DropIndex(liveTabID, "customers", pkName, false); err == nil {
			t.Fatal("the primary key's index was droppable as an index")
		} else {
			t.Logf("refused: %v", err)
		}
	})

	t.Run("add, edit and drop constraints of every type", func(t *testing.T) {
		exec(t, c, `DELETE FROM customers`)

		cases := []model.ConstraintDefinition{
			{Name: "customers_state_unique", Type: "UNIQUE", Definition: "UNIQUE (state)"},
			{Name: "customers_state_check", Type: "CHECK", Definition: "CHECK (length(state) < 32)", Comment: "short states"},
			{Name: "customers_c28_excl", Type: "EXCLUDE", Definition: "EXCLUDE USING gist (c28 WITH &&)"},
		}
		for _, def := range cases {
			if err := c.AddConstraint(liveTabID, "customers", def); err != nil {
				t.Fatalf("AddConstraint %s: %v", def.Name, err)
			}
			got, err := c.GetConstraintDefinition(liveTabID, "customers", def.Name)
			if err != nil {
				t.Fatalf("GetConstraintDefinition %s: %v", def.Name, err)
			}
			t.Logf("%-28s %-11s %s", got.Name, got.Type, got.Definition)
		}

		// A foreign key, added and then given an ON DELETE action.
		fk := model.ConstraintDefinition{
			Name: "orders_customer_fk", Type: "FOREIGN KEY",
			Definition: "FOREIGN KEY (customer_id) REFERENCES customers (id)",
		}
		if err := c.AddConstraint(liveTabID, "orders", fk); err != nil {
			t.Fatalf("AddConstraint fk: %v", err)
		}
		fk.Definition = "FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE"
		if err := c.UpdateConstraint(liveTabID, "orders", "orders_customer_fk", fk); err != nil {
			t.Fatalf("UpdateConstraint fk: %v", err)
		}
		got, err := c.GetConstraintDefinition(liveTabID, "orders", "orders_customer_fk")
		if err != nil {
			t.Fatalf("GetConstraintDefinition fk: %v", err)
		}
		if got.Definition != "FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE" {
			t.Fatalf("ON DELETE did not land: %q", got.Definition)
		}
		t.Logf("fk now: %s", got.Definition)

		// Rename only.
		got.Name = "orders_customer_fkey2"
		if err := c.UpdateConstraint(liveTabID, "orders", "orders_customer_fk", *got); err != nil {
			t.Fatalf("rename UpdateConstraint: %v", err)
		}
		if _, err := c.GetConstraintDefinition(liveTabID, "orders", "orders_customer_fkey2"); err != nil {
			t.Fatalf("renamed constraint missing: %v", err)
		}

		// NOT VALID, and the round trip that splits it back off the body.
		exec(t, c, `INSERT INTO customers (state) VALUES ('too-long')`)
		notValid := model.ConstraintDefinition{
			Name: "customers_state_len", Type: "CHECK",
			Definition: "CHECK (length(state) < 5)", NotValid: true,
		}
		if err := c.AddConstraint(liveTabID, "customers", notValid); err != nil {
			t.Fatalf("NOT VALID AddConstraint: %v", err)
		}
		back, err := c.GetConstraintDefinition(liveTabID, "customers", "customers_state_len")
		if err != nil {
			t.Fatalf("GetConstraintDefinition: %v", err)
		}
		if !back.NotValid || back.IsValidated {
			t.Fatalf("NOT VALID lost on the way back: %+v", *back)
		}
		t.Logf("NOT VALID round-tripped as definition=%q notValid=%v", back.Definition, back.NotValid)

		// The same check without NOT VALID must be refused, and the original must survive.
		valid := notValid
		valid.NotValid = false
		if err := c.UpdateConstraint(liveTabID, "customers", "customers_state_len", valid); err == nil {
			t.Fatal("a check the existing rows fail was accepted")
		} else {
			t.Logf("refused validation: %v", err)
		}
		if _, err := c.GetConstraintDefinition(liveTabID, "customers", "customers_state_len"); err != nil {
			t.Fatalf("the original constraint was dropped by a failed edit: %v", err)
		}
		t.Log("the failed replacement rolled back and left the original standing")

		// Saving back exactly what postgres printed must be recognised as a no-op,
		// which is what keeps a comment-only edit from rebuilding the constraint.
		stored, err := c.GetConstraintDefinition(liveTabID, "orders", "orders_customer_fkey2")
		if err != nil {
			t.Fatalf("GetConstraintDefinition: %v", err)
		}
		if err := c.UpdateConstraint(liveTabID, "orders", stored.Name, *stored); err == nil {
			t.Fatal("an unchanged save was treated as a change")
		} else {
			t.Logf("unchanged save reported: %v", err)
		}

		if err := c.DropConstraint(liveTabID, "customers", "customers_state_len", false); err != nil {
			t.Fatalf("DropConstraint: %v", err)
		}
		if err := c.DropConstraint(liveTabID, "customers", "customers_state_unique", true); err != nil {
			t.Fatalf("cascade DropConstraint: %v", err)
		}
		t.Log("constraints dropped under RESTRICT and CASCADE")
	})

	t.Run("the manage view still reads back", func(t *testing.T) {
		info, err := c.GetTableInfo(liveTabID, "customers")
		if err != nil {
			t.Fatalf("GetTableInfo: %v", err)
		}
		found := false
		for _, column := range info.Indexes.Columns {
			if column == "is_constraint" {
				found = true
			}
		}
		if !found {
			t.Fatal("is_constraint is missing from the indexes grid")
		}
		t.Logf("structure=%d rows, indexes=%d rows (%v), rules=%d rows",
			len(info.Structure.Rows), len(info.Indexes.Rows), info.Indexes.Columns, len(info.Rules.Rows))
		for _, row := range info.Rules.Rows {
			for _, cell := range row {
				if cell.Column == "constraint_type" && cell.Value == "EXCLUDE" {
					t.Log("exclusion constraint is labelled EXCLUDE, matching the editor")
				}
			}
		}
	})
}

// TestLiveTypeModifiers checks the base names the column form's splitter produces are
// types the picker actually offers, that acceptsModifier is set on exactly the ones
// that take a modifier, and that each reassembled type is accepted by AddColumn.
func TestLiveTypeModifiers(t *testing.T) {
	c, cleanup := liveConnections(t)
	defer cleanup()

	exec(t, c, `DROP TABLE IF EXISTS modifiers CASCADE`)
	exec(t, c, `CREATE TABLE modifiers (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)`)

	options, err := c.GetSchemaEditorOptions(liveTabID)
	if err != nil {
		t.Fatalf("GetSchemaEditorOptions: %v", err)
	}
	byName := map[string]model.TypeOption{}
	for _, option := range options.Types {
		byName[option.Name] = option
	}

	// base name the splitter yields -> does the picker list it, should it show a
	// modifier box, and what should the reassembled type be.
	cases := []struct {
		base           string
		modifier       string
		suffix         string
		want           string
		expectInPicker bool
	}{
		{"character varying", "255", "", "character varying(255)", true},
		{"character", "3", "", "character(3)", true},
		{"numeric", "10,2", "", "numeric(10,2)", true},
		{"bit", "4", "", "bit(4)", true},
		{"bit varying", "8", "", "bit varying(8)", true},
		{"timestamp without time zone", "3", "", "timestamp(3) without time zone", true},
		{"timestamp with time zone", "3", "", "timestamp(3) with time zone", true},
		{"time without time zone", "3", "", "time(3) without time zone", true},
		{"time with time zone", "3", "", "time(3) with time zone", true},
		{"interval", "3", "", "interval(3)", true},
		{"character varying", "32", "[]", "character varying(32)[]", true},
		{"numeric", "8,4", "[]", "numeric(8,4)[]", true},
		{"timestamp without time zone", "3", "[]", "timestamp(3) without time zone[]", true},
		{"character varying", "", "", "character varying", true},
		{"text", "", "[]", "text[]", true},
		// Not a catalog name; the form keeps the modifier box open for it anyway.
		{"interval second", "3", "", "interval second(3)", false},
	}

	for i, tc := range cases {
		option, listed := byName[tc.base]
		if listed != tc.expectInPicker {
			t.Fatalf("%q: listed in picker = %v, expected %v", tc.base, listed, tc.expectInPicker)
		}
		// Only a case that actually carries a modifier needs the box to be offered.
		if tc.modifier != "" && listed && !option.AcceptsModifier {
			t.Fatalf("%q is listed but acceptsModifier is false, so the length box would be hidden", tc.base)
		}

		name := fmt.Sprintf("m%02d", i)
		if err := c.AddColumn(liveTabID, "modifiers", model.ColumnDefinition{
			Name: name, DataType: tc.want, IsNullable: true,
		}); err != nil {
			t.Fatalf("AddColumn %s %s: %v", name, tc.want, err)
		}
		got := scalar(t, c, fmt.Sprintf(
			`SELECT format_type(atttypid, atttypmod) FROM pg_attribute
			 WHERE attrelid = 'public.modifiers'::regclass AND attname = '%s'`, name))
		if got != tc.want {
			t.Fatalf("%s: sent %q, postgres stored %q", name, tc.want, got)
		}
		t.Logf("%-30s + %-5s %-2s -> %-32s stored as %s", tc.base, tc.modifier, tc.suffix, tc.want, got)
	}

	// Types that take no modifier must not show the box.
	for _, name := range []string{"text", "integer", "boolean", "uuid", "jsonb", "date", "bytea"} {
		option, listed := byName[name]
		if !listed {
			t.Fatalf("%q missing from the picker", name)
		}
		if option.AcceptsModifier {
			t.Fatalf("%q offers a modifier box but takes no modifier", name)
		}
	}
	t.Log("text/integer/boolean/uuid/jsonb/date/bytea correctly show no modifier box")

	// Editing a varchar's length is a plain retype that keeps the data.
	exec(t, c, `INSERT INTO modifiers (m00) VALUES ('kept')`)
	if err := c.UpdateColumn(liveTabID, "modifiers", "m00", model.ColumnDefinition{
		Name: "m00", DataType: "character varying(8)", IsNullable: true,
	}); err != nil {
		t.Fatalf("shrink UpdateColumn: %v", err)
	}
	if kept := scalar(t, c, `SELECT m00 FROM modifiers WHERE m00 IS NOT NULL`); kept != "kept" {
		t.Fatalf("value lost shrinking the length: %q", kept)
	}
	if err := c.UpdateColumn(liveTabID, "modifiers", "m00", model.ColumnDefinition{
		Name: "m00", DataType: "character varying(2)", IsNullable: true,
	}); err == nil {
		t.Fatal("shrinking below the stored value was accepted")
	} else {
		t.Logf("shrinking too far refused: %v", err)
	}
	t.Log("length 255 -> 8 kept the data; 8 -> 2 was refused and rolled back")
}
